### ISSUE TITLE
请教一个问题。

### ISSUE THREAD

**Issue by SuKaipeng** [baidu-tookapill/Task-2-23#2]
Task-2-23/task.js
第23行  node = nodeList[BFindex++];
加了这一行以后递归函数的执行顺序才不会出错。请问这是为什么，没想明白，谢谢🙏

**Comment by ChaoYuLeo** [comment]
其实很简单，你在脑子里照着这个逻辑跑一遍基本就明白了。
这个代码其实是两个表达式，node = nodeList[BFindex] 和 BFindex += 1。
因为是广度优先遍历，我们首先是往兄弟节点（准确说是没有元素兄弟节点）的方向遍历的。
第一次传入的是根节点，由于根元素没有兄弟节点，所以 **traverseBF(node.nextElementSibling, nodeList);** 这一句就跳过了，然后执行到 **node = nodeList[BFindex++];** 由于前面 **nodeList.push(node);** 把根节点推入到了nodeList里，这里我们这一行代码其实并没有什么意思，再看下一行，`traverseBF(node.firstElementChild, nodeList);` 这里把根节点的第一个元素节点和nodeList传入该函数。
又回到刚才的步骤，我们将这个元素推入nodeList，然后再推他的兄弟、兄弟的兄弟。一直推到完。
推完以后又执行到这一行 `node = nodeList[BFindex++];` ，此时BFindex是1咯，也就是说我们下一行传入node其实也就是nodeList[1]做什么？此时nodeList[1]里是什么？
nodeList[1]是父节点的第一个子节点，我们传入这个节点，并对他的第一个子节点重复刚才的操作（不断推入第一个子节点的兄弟节点、兄兄弟节点。。。）。然后再下面就是nodeList[2]执行这个步骤。
一直重复这样的步骤，相当于我们从上到下一（从外到内）层一层的走完了整个树。

感觉用文字来描述还是不太准确啊QAQ。有什么不懂的再说吧。。。

**Comment by SuKaipeng** [comment]
谢谢，我明白了。主要是我不太理解两个递归函数的执行顺序。
现在我懂了。我之前是以为，一开始函数传入根节点，然后根节点的nextElementSibling传入traverseBF(node.nextElementSibling, nodeList); 。接着函数就执行node = nodeList[BFindex++]; traverseBF(node.firstElementChild, nodeList);。。。所以之前我自己认为的node = nodeList[BFindex++];没什么意义。
其实简单来说，两个递归函数的执行顺序是第一个递归函数一直递归到底，才会有再执行第二个递归函数。不知道这样理解是否准确？

**Comment by ChaoYuLeo** [comment]
对的，这样理解就没有问题了。 发自网易邮箱大师 在2017年01月17日 17:58，SuKaipeng 写道： 谢谢，我明白了。主要是我不太理解两个递归函数的执行顺序。 现在我懂了。我之前是以为，一开始函数传入根节点，然后根节点的nextElementSibling传入traverseBF(node.nextElementSibling, nodeList); 。接着函数就执行node = nodeList[BFindex++]; traverseBF(node.firstElementChild, nodeList);。。。所以之前我自己认为的node = nodeList[BFindex++];没什么意义。 其实简单来说，两个递归函数的执行顺序是第一个递归函数一直递归到底，才会有再执行第二个递归函数。不知道这样理解是否准确？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by SuKaipeng** [comment]
OK。🙏谢谢。我看你们团队怎么才做到task 25呀，后面都没做了……想找个前辈学习下哈哈

发自我的 iPhone

**Comment by ChaoYuLeo** [comment]
因为就两个人做啊，我做了前面的，另一个做了寻路那几题。后面没时间咯。 发自网易邮箱大师 在2017年01月17日 18:13，SuKaipeng 写道： OK。🙏谢谢。我看你们团队怎么才做到task 25呀，后面都没做了……想找个前辈学习下哈哈 发自我的 iPhone > 在 2017年1月17日，下午6:07，LeoYu <notifications@github.com> 写道： > > 对的，这样理解就没有问题了。 发自网易邮箱大师 在2017年01月17日 17:58，SuKaipeng 写道： 谢谢，我明白了。主要是我不太理解两个递归函数的执行顺序。 现在我懂了。我之前是以为，一开始函数传入根节点，然后根节点的nextElementSibling传入traverseBF(node.nextElementSibling, nodeList); 。接着函数就执行node = nodeList[BFindex++]; traverseBF(node.firstElementChild, nodeList);。。。所以之前我自己认为的node = nodeList[BFindex++];没什么意义。 其实简单来说，两个递归函数的执行顺序是第一个递归函数一直递归到底，才会有再执行第二个递归函数。不知道这样理解是否准确？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. > — > You are receiving this because you authored the thread. > Reply to this email directly, view it on GitHub, or mute the thread. > — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
